include("../8_PostEstimation/compute_hist_decomp.jl")
include("../8_PostEstimation/compute_irfs_vardecomp.jl")
include("../8_PostEstimation/compute_vardecomp_bounds.jl")
include("../8_PostEstimation/plot_irfs.jl")
include("../8_PostEstimation/plot_vardecomp.jl")
include("../8_PostEstimation/compute_bcfreq_vardecomp.jl")